name: portfolio_web
description: A professional portfolio website showcasing mobile development expertise.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.6.0
  url_launcher: ^6.2.1
  visibility_detector: ^0.4.0+2
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
